platform:ios, '9.0'
use_frameworks!

target 'HCSecurityKeyboardExcemple' do
  pod 'HCSecurityKeyboard', :git => 'https://git.homecreditcfc.cn/it-dev/hcc-open-source/fe/ios/hcsecuritykeyboard',
:branch => 'master'
end
