# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HCSecurityKeyboardDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HCSecurityKeyboardDemo
  pod 'HCSecurityKeyboard', :git => 'https://github.com/hccxc/secure-keyboard-ios',
:branch => 'main'
end
